trigger:
- none

pool:
  vmImage: 'Ubuntu-latest'

variables:
  buildProjects: '**/src/**/*.csproj'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 8'
  inputs:
    packageType: sdk
    version: 8.0.x

- task: DotNetCoreCLI@2
  displayName: Build Release
  inputs:
    command: 'build'
    arguments: /p:Configuration=$(buildConfiguration)
    projects: $(buildProjects)

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  condition: succeeded()
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'